Login and UKI updates (#2242)
* Change DM to SDDM

* Move to custom named UKI

* Skip creation on Mac

* Add entry to make sure VSCode uses gnome keyring

* Fix order for UKI generation

* Limine only

* BTRFS only

* Add checks for possible issues

* Remove

* Add verification to omarchy-pkg-add and speed up installs

* Use omarchy-pkg-add

* Update files to include dirs

* Fix relaunch

diff --git a/bin/omarchy-pkg-add b/bin/omarchy-pkg-add
--- a/bin/omarchy-pkg-add
+++ b/bin/omarchy-pkg-add
@@ -1,8 +1,12 @@
 #!/bin/bash
 
+sudo pacman -S --noconfirm --needed "$@" || exit 1
+
 for pkg in "$@"; do
+  # Secondary check to handle states where pacman doesn't actually register an error
   if ! pacman -Q "$pkg" &>/dev/null; then
-    sudo pacman -S --noconfirm "$pkg" || exit 1
+    echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
+    exit 1
   fi
 done
 
